# Generated by Django 5.1 on 2024-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_car_owner_moto_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='description',
            field=models.TextField(unique=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='название'),
        ),
    ]
